#!/usr/bin/env python3
"""
Season Archive: Export immutable annual snapshot of NBA season data.

Outputs (written to ARCHIVE_DIR, default ./season_archive):
  - games_{SEASON}.csv
  - game_stats_{SEASON}.csv
  - team_stats_{SEASON}.csv
  - stat_rankings_{SEASON}.csv
  - checksums_{SEASON}.txt  (SHA-256 of each CSV)
"""
import csv
import hashlib
import os
import re
import sys
import psycopg2
from psycopg2.extras import RealDictCursor

SEASON = os.getenv('ARCHIVE_SEASON') or os.getenv('CURRENT_SEASON', '')
ARCHIVE_DIR = os.getenv('ARCHIVE_DIR', 'season_archive')

TABLES = [
    ('games',         'SELECT * FROM games WHERE season = %s ORDER BY game_date, game_id'),
    ('game_stats',    'SELECT * FROM game_stats WHERE season = %s ORDER BY game_date, team_id'),
    ('team_stats',    'SELECT * FROM team_stats WHERE season = %s ORDER BY team_id'),
    ('stat_rankings', 'SELECT * FROM stat_rankings WHERE season = %s ORDER BY stat_category, rank'),
]


def connect_db():
    database_url = os.getenv('DATABASE_URL', '')
    if database_url:
        match = re.search(r'@([^:/]+)', database_url)
        host = match.group(1) if match else 'unknown'
        print(f"  🔌 Connecting to database: {host}")
        return psycopg2.connect(database_url)
    else:
        host = os.getenv('DB_HOST', 'localhost')
        print(f"  🔌 Connecting to database: {host}")
        return psycopg2.connect(
            host=host,
            port=int(os.getenv('DB_PORT', 5432)),
            user=os.getenv('DB_USER', 'postgres'),
            password=os.getenv('DB_PASSWORD', ''),
            database=os.getenv('DB_NAME', 'nba_stats'),
        )


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(65536), b''):
            h.update(chunk)
    return h.hexdigest()


def export_csv(cursor, table_name, query, season, out_dir):
    filename = f"{table_name}_{season}.csv"
    path = os.path.join(out_dir, filename)
    cursor.execute(query, (season,))
    rows = cursor.fetchall()
    if not rows:
        print(f"  ⚠️  No rows found in {table_name} for season {season}")
        with open(path, 'w', newline='') as f:
            pass
        return filename, path, 0
    col_names = [desc[0] for desc in cursor.description]
    with open(path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(col_names)
        writer.writerows(rows)
    print(f"  ✅ {filename} — {len(rows):,} rows")
    return filename, path, len(rows)


def main():
    if not SEASON:
        print("❌ ARCHIVE_SEASON or CURRENT_SEASON env var is required.")
        sys.exit(1)

    print(f"\n{'=' * 60}")
    print(f"SEASON ARCHIVE: {SEASON}")
    print(f"{'=' * 60}")

    os.makedirs(ARCHIVE_DIR, exist_ok=True)
    print(f"\n📁 Output directory: {ARCHIVE_DIR}")

    conn = connect_db()
    cursor = conn.cursor()

    exported = []
    print("\n📦 Exporting CSVs...")
    for table_name, query in TABLES:
        filename, path, row_count = export_csv(cursor, table_name, query, SEASON, ARCHIVE_DIR)
        exported.append((filename, path, row_count))

    cursor.close()
    conn.close()

    # Generate checksum manifest
    checksum_filename = f"checksums_{SEASON}.txt"
    checksum_path = os.path.join(ARCHIVE_DIR, checksum_filename)
    print(f"\n🔐 Generating checksum manifest: {checksum_filename}")
    with open(checksum_path, 'w', encoding='utf-8') as f:
        f.write(f"# SHA-256 checksums — NBA Season {SEASON} archive\n")
        f.write(f"# Generated by archive_season.py\n\n")
        for filename, path, _ in exported:
            digest = sha256_file(path)
            f.write(f"{digest}  {filename}\n")
            print(f"  {digest[:12]}...  {filename}")

    print(f"\n✅ Season {SEASON} archive complete — {len(exported)} CSV files + checksum manifest")
    print(f"   Verify with: sha256sum -c {checksum_filename}")


if __name__ == '__main__':
    main()
